# Generated by Django 4.0.1 on 2022-01-27 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('images', models.ImageField(upload_to='blog/images')),
                ('date_time', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
    ]
